import type { Config } from "tailwindcss"

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "ink-page": "var(--ink-page)",
        "ink-page-text": "var(--ink-page-text)",
        "ink-canvas": "var(--ink-canvas)",
        "ink-canvas-dim": "var(--ink-canvas-dim)",
        "ink-canvas-bright": "var(--ink-canvas-bright)",
        "ink-panel-flat": "var(--ink-panel-flat)",
        "ink-panel-soft": "var(--ink-panel-soft)",
        "ink-panel": "var(--ink-panel)",
        "ink-panel-raised": "var(--ink-panel-raised)",
        "ink-panel-lifted": "var(--ink-panel-lifted)",
        "ink-text": "var(--ink-text)",
        "ink-text-muted": "var(--ink-text-muted)",
        "ink-canvas-inverse": "var(--ink-canvas-inverse)",
        "ink-text-inverse": "var(--ink-text-inverse)",
        "ink-border": "var(--ink-border)",
        "ink-border-soft": "var(--ink-border-soft)",
        "ink-tint": "var(--ink-tint)",
        "brand-primary": "var(--brand-primary)",
        "brand-primary-text": "var(--brand-primary-text)",
        "brand-primary-soft": "var(--brand-primary-soft)",
        "brand-primary-soft-text": "var(--brand-primary-soft-text)",
        "brand-primary-inverse": "var(--brand-primary-inverse)",
        "brand-secondary": "var(--brand-secondary)",
        "brand-secondary-text": "var(--brand-secondary-text)",
        "brand-secondary-soft": "var(--brand-secondary-soft)",
        "brand-secondary-soft-text": "var(--brand-secondary-soft-text)",
        "brand-tertiary": "var(--brand-tertiary)",
        "brand-tertiary-text": "var(--brand-tertiary-text)",
        "brand-tertiary-soft": "var(--brand-tertiary-soft)",
        "brand-tertiary-soft-text": "var(--brand-tertiary-soft-text)",
        "status-error": "var(--status-error)",
        "status-error-text": "var(--status-error-text)",
        "status-error-soft": "var(--status-error-soft)",
        "status-error-soft-text": "var(--status-error-soft-text)",
        "status-success": "var(--status-success)",
        "status-success-text": "var(--status-success-text)",
        "status-success-soft": "var(--status-success-soft)",
        "status-success-soft-text": "var(--status-success-soft-text)",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "sans-serif"],
      },
    },
  },
}

export default config
