"""
Harness contracts for Phase 6 second-pass review remediation tasks T-086 through T-096.

Every test is RED before its corresponding task is implemented and GREEN after.
Do not edit this file unless the spec, plan, or review finding has changed.

Second-pass review finding references:
  T-086 — CI breakage: black + ruff violations from Phase 5 commits
  T-087 — SSE catch-all discloses raw exception detail to browser
  T-088 — Double-refund race: no DB-level unique constraint on credit_ledger
  T-089 — Recovery heuristic: 60-second time window instead of stored ledger ID
  T-090 — Observability env vars required, crashes on fresh deploy
  T-094 — WorkspaceService._load() footgun (user_id-free query path)
  T-095 — Double RS256 decode per request (rate limiter + auth dependency)
  T-096 — Fragile _where_criteria introspection in workspace test mock
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

import pytest

from conftest import import_backend, read_backend_file


REPO_ROOT = Path(__file__).resolve().parents[3]
BACKEND_ROOT = REPO_ROOT / "backend"
FRONTEND_SRC = REPO_ROOT / "frontend" / "src"


# ---------------------------------------------------------------------------
# T-086 [CI] — Black formatting and Ruff E501 violations must be fixed
# ---------------------------------------------------------------------------


def test_stream_stage_helper_sse_yield_lines_fit_within_88_chars() -> None:
    """
    Each SSE yield statement in _stream_stage() must fit within 88 characters.
    Long f-string yields break ruff's E501 check and block CI.
    The fix is to extract the JSON payload into a local variable before yielding.
    """
    source = read_backend_file("routers", "stage.py")

    stream_start = source.find("async def _stream_stage")
    assert stream_start != -1, "routers/stage.py must define _stream_stage"

    next_def = source.find("\nasync def ", stream_start + 1)
    stream_body = source[stream_start:next_def] if next_def != -1 else source[stream_start:]

    long_yield_lines = [
        line for line in stream_body.splitlines()
        if line.strip().startswith("yield") and len(line) > 88
    ]
    assert not long_yield_lines, (
        f"_stream_stage() has {len(long_yield_lines)} yield line(s) exceeding 88 chars: "
        f"{long_yield_lines[:2]}. "
        "Extract JSON dicts into local variables before yielding. "
        "See T-086."
    )


def test_stage_manager_has_blank_lines_after_log_eval_error() -> None:
    """
    _log_eval_error() must be followed by two blank lines before the next
    module-level definition. black inserts these automatically; their absence
    indicates the file was never black-formatted after T-080.
    """
    source = read_backend_file("services", "pipeline", "stage_manager.py")

    func_start = source.find("def _log_eval_error")
    assert func_start != -1, "stage_manager.py must define _log_eval_error"

    # Find the end of the function body (next top-level def or class or constant)
    after_func = source[func_start:]
    # Collect lines after the function definition
    lines = after_func.splitlines()
    func_end_idx = None
    for i, line in enumerate(lines[1:], start=1):
        if line and not line.startswith(" ") and not line.startswith("\t"):
            func_end_idx = i
            break

    assert func_end_idx is not None, "_log_eval_error must be followed by more module content"

    # The two lines immediately before the next definition should be blank
    separator_lines = lines[func_end_idx - 2:func_end_idx]
    assert all(l == "" for l in separator_lines), (
        f"_log_eval_error is not followed by two blank lines before the next definition. "
        f"Lines before next def: {separator_lines!r}. "
        "Run `black .` in backend/ to fix. See T-086."
    )


# ---------------------------------------------------------------------------
# T-087 [Security] — SSE catch-all must not expose raw exception detail
# ---------------------------------------------------------------------------


def test_stream_stage_catch_all_does_not_yield_str_exc() -> None:
    """
    The except Exception branch in _stream_stage() must not send str(exc) to the client.
    Raw Python exception messages can contain DB connection strings, ORM internals, etc.
    """
    source = read_backend_file("routers", "stage.py")

    stream_start = source.find("async def _stream_stage")
    assert stream_start != -1, "routers/stage.py must define _stream_stage"

    next_def = source.find("\nasync def ", stream_start + 1)
    stream_body = source[stream_start:next_def] if next_def != -1 else source[stream_start:]

    # Find the catch-all except block
    except_match = re.search(r"except Exception.*?:", stream_body)
    assert except_match is not None, (
        "_stream_stage() has no catch-all except block. "
        "The catch-all must exist but not disclose exc detail. See T-087."
    )

    except_start = except_match.start()
    # Look at the yield within ~10 lines after the except
    catchall_area = stream_body[except_start:except_start + 400]

    # The dangerous pattern: str(exc) inside a yield
    assert "str(exc)" not in catchall_area, (
        "_stream_stage() catch-all yields str(exc) — raw exception message sent to browser. "
        "Replace with a fixed {'error': 'internal_error'} event and log server-side. "
        "See T-087."
    )

    assert '"detail"' not in catchall_area or "internal_error" not in catchall_area.split('"detail"')[0], (
        "_stream_stage() catch-all still includes a 'detail' field in the error event. "
        "Remove the detail field; only include {'error': 'internal_error'}. "
        "See T-087."
    )


def test_stream_stage_catch_all_logs_exception_server_side() -> None:
    """
    When the catch-all fires, the exception must be logged with full context server-side.
    Silent swallowing is also unacceptable — the error must appear in structured logs.
    """
    source = read_backend_file("routers", "stage.py")

    stream_start = source.find("async def _stream_stage")
    next_def = source.find("\nasync def ", stream_start + 1)
    stream_body = source[stream_start:next_def] if next_def != -1 else source[stream_start:]

    except_match = re.search(r"except Exception.*?:", stream_body)
    assert except_match is not None

    catchall_area = stream_body[except_match.start():except_match.start() + 400]

    has_logging = (
        "logger.exception" in catchall_area
        or "log.exception" in catchall_area
        or "logger.error" in catchall_area
        or "logging.exception" in catchall_area
    )
    assert has_logging, (
        "_stream_stage() catch-all does not log the exception. "
        "Call logger.exception(...) so the error appears in structured logs. "
        "See T-087."
    )


# ---------------------------------------------------------------------------
# T-088 [Financial] — credit_ledger must have DB-level unique constraint
# ---------------------------------------------------------------------------


def test_credit_ledger_model_has_unique_refund_index_on_user_reason() -> None:
    """
    CreditLedger must declare a unique refund-scoped index on (user_id, reason).
    Without a DB-level constraint, two concurrent refund() calls can both pass the
    application-level pre-check and double-insert, creating a double-credit.
    """
    source = read_backend_file("models", "credit_ledger.py")

    assert "Index" in source, (
        "models/credit_ledger.py does not import or use Index. "
        "Add a unique partial Index on ('user_id', 'reason') for refund rows."
    )

    assert "__table_args__" in source, (
        "CreditLedger model has no __table_args__. "
        "Add __table_args__ with the unique refund index."
    )

    index_area_match = re.search(r"Index\([^)]+\)", source, re.DOTALL)
    assert index_area_match is not None, (
        "Index is imported but no Index(...) call found."
    )
    index_call = index_area_match.group(0)
    assert "user_id" in index_call and "reason" in index_call, (
        f"Refund index does not cover both user_id and reason: {index_call!r}."
    )
    assert "postgresql_where" in index_call and "refund" in index_call, (
        f"Refund index must be partial and scoped to refund rows: {index_call!r}."
    )


def test_migration_0003_creates_credit_ledger_unique_constraint() -> None:
    """
    Alembic migration 0003 must create the uq_credit_ledger_user_reason constraint.
    """
    versions_dir = BACKEND_ROOT / "migrations" / "versions"
    assert versions_dir.exists()

    migration_0003 = next(
        (f for f in sorted(versions_dir.glob("*.py")) if f.name.startswith("0003_")),
        None,
    )
    assert migration_0003 is not None, (
        "No migration file starting with '0003_' found. "
        "Create 0003_credit_ledger_unique_refund.py. See T-088."
    )

    content = migration_0003.read_text(encoding="utf-8")
    assert "create_unique_constraint" in content or "UniqueConstraint" in content, (
        f"{migration_0003.name} does not call create_unique_constraint. See T-088."
    )
    assert "credit_ledger" in content, (
        f"{migration_0003.name} does not reference credit_ledger table. See T-088."
    )


def test_credit_service_refund_handles_integrity_error_silently() -> None:
    """
    refund() must catch IntegrityError (from a concurrent duplicate insert)
    and return silently — it must not propagate the exception to the caller.
    The DB constraint is the authoritative guard; the app layer handles the race.
    """
    source = read_backend_file("services", "credit_service.py")

    refund_start = source.find("async def refund")
    assert refund_start != -1, "credit_service.py must define async def refund"

    next_method = source.find("\n    async def ", refund_start + 1)
    refund_body = source[refund_start:next_method] if next_method != -1 else source[refund_start:]

    assert "IntegrityError" in refund_body, (
        "credit_service.refund() does not handle IntegrityError. "
        "Wrap the db.add/flush in try/except IntegrityError to make the race safe. "
        "See T-088."
    )


def test_credit_service_refund_removes_pre_check_select() -> None:
    """
    After adding the DB-level constraint, the application-level pre-check SELECT
    in refund() is redundant overhead and must be removed.
    The constraint is the sole guard; the app catches IntegrityError.
    The remaining SELECT in refund() is for looking up the original deduction entry
    by ID — that is still necessary. The removed pre-check was a second SELECT that
    queried for an existing refund row by (user_id, reason).
    """
    source = read_backend_file("services", "credit_service.py")

    refund_start = source.find("async def refund")
    assert refund_start != -1

    next_method = source.find("\n    async def ", refund_start + 1)
    refund_body = source[refund_start:next_method] if next_method != -1 else source[refund_start:]

    # The pre-check pattern: a SELECT that looks for existing refund rows by reason field.
    # This is distinguishable from the necessary original-entry lookup (by ID).
    # After T-088, there must be only ONE execute() call (to find the original by ID),
    # not a second one searching by reason/existing.
    execute_count = refund_body.count("await db.execute(")
    assert execute_count <= 1, (
        f"credit_service.refund() contains {execute_count} db.execute() calls. "
        "The pre-check SELECT (second execute) must be removed. "
        "The UniqueConstraint + IntegrityError catch is the sole guard. "
        "See T-088."
    )


# ---------------------------------------------------------------------------
# T-089 [Financial] — Recovery service must use stored deduction_ledger_id
# ---------------------------------------------------------------------------


def test_stage_model_has_deduction_ledger_id_column() -> None:
    """
    Stage model must have a nullable deduction_ledger_id FK column so the
    recovery service can refund the exact ledger entry without a time-window guess.
    """
    source = read_backend_file("models", "stage.py")

    assert "deduction_ledger_id" in source, (
        "models/stage.py does not define deduction_ledger_id column. "
        "Add deduction_ledger_id: Mapped[UUID | None] = mapped_column(..., nullable=True). "
        "See T-089."
    )

    assert "nullable=True" in source or "Optional" in source or "| None" in source, (
        "deduction_ledger_id must be nullable (FK can be unset before first generation). "
        "See T-089."
    )


def test_migration_0004_adds_stage_deduction_ledger_id() -> None:
    """
    Alembic migration 0004 must add deduction_ledger_id column to the stages table.
    """
    versions_dir = BACKEND_ROOT / "migrations" / "versions"
    assert versions_dir.exists()

    migration_0004 = next(
        (f for f in sorted(versions_dir.glob("*.py")) if f.name.startswith("0004_")),
        None,
    )
    assert migration_0004 is not None, (
        "No migration file starting with '0004_' found. "
        "Create 0004_stage_deduction_ledger_id.py. See T-089."
    )

    content = migration_0004.read_text(encoding="utf-8")
    assert "deduction_ledger_id" in content, (
        f"{migration_0004.name} does not add deduction_ledger_id column. See T-089."
    )
    assert "stages" in content, (
        f"{migration_0004.name} does not reference the stages table. See T-089."
    )


def test_stage_manager_generate_sets_deduction_ledger_id() -> None:
    """
    stage_manager.generate() must set stage.deduction_ledger_id after deducting credits,
    so the recovery service can find the exact entry to refund.
    """
    source = read_backend_file("services", "pipeline", "stage_manager.py")

    generate_start = source.find("async def generate")
    assert generate_start != -1, "stage_manager.py must define async def generate"

    next_method = source.find("\n    async def ", generate_start + 1)
    if next_method == -1:
        next_method = source.find("\nasync def ", generate_start + 1)
    generate_body = source[generate_start:next_method] if next_method != -1 else source[generate_start:]

    assert "deduction_ledger_id" in generate_body, (
        "stage_manager.generate() does not set stage.deduction_ledger_id after deducting. "
        "Add: stage.deduction_ledger_id = deduction.id "
        "immediately after credit_service.deduct(). See T-089."
    )


def test_recovery_service_does_not_use_timedelta_window() -> None:
    """
    recover_stuck_stages() must not use a timedelta time window to find the credit entry.
    Clock drift and high load make the window unreliable. Use stage.deduction_ledger_id.
    """
    source = read_backend_file("services", "pipeline", "recovery_service.py")

    # The heuristic pattern: CreditLedger.created_at >= stage.updated_at - timedelta(seconds=N)
    has_time_window = (
        "timedelta(seconds=" in source
        and "created_at" in source
        and "updated_at" in source
    )
    assert not has_time_window, (
        "recovery_service.py still uses a timedelta time-window to find the credit entry. "
        "Replace with stage.deduction_ledger_id direct lookup. See T-089."
    )


def test_recovery_service_uses_deduction_ledger_id() -> None:
    """
    recover_stuck_stages() must reference stage.deduction_ledger_id to identify
    the exact credit entry to refund.
    """
    source = read_backend_file("services", "pipeline", "recovery_service.py")

    assert "deduction_ledger_id" in source, (
        "recovery_service.py does not reference deduction_ledger_id. "
        "Replace the time-window heuristic with: "
        "if stage.deduction_ledger_id: await credit_service.refund(db, stage.deduction_ledger_id). "
        "See T-089."
    )


# ---------------------------------------------------------------------------
# T-090 [Reliability] — Observability env vars must be optional
# ---------------------------------------------------------------------------


def test_config_sentry_dsn_has_default_empty_string() -> None:
    """
    config.py must declare sentry_dsn with a default of "" so the app starts
    without a Sentry DSN configured (local dev, basic staging environments).
    """
    source = read_backend_file("config.py")

    sentry_match = re.search(r'sentry_dsn\s*:\s*str\s*=\s*"([^"]*)"', source)
    if sentry_match is None:
        sentry_match = re.search(r"sentry_dsn\s*:\s*str\s*=\s*'([^']*)'", source)

    assert sentry_match is not None, (
        "config.py declares sentry_dsn without a default value. "
        "Change to: sentry_dsn: str = '' "
        "See T-090."
    )
    # The default value should be an empty string (not a placeholder URL)
    default_val = sentry_match.group(1)
    assert not default_val.startswith("http"), (
        f"sentry_dsn default is '{default_val}' — a URL placeholder. "
        "Use empty string ''. See T-090."
    )


def test_config_grafana_otlp_endpoint_has_default_empty_string() -> None:
    """
    config.py must declare grafana_otlp_endpoint with a default of "".
    """
    source = read_backend_file("config.py")

    otlp_match = re.search(r'grafana_otlp_endpoint\s*:\s*str\s*=\s*"([^"]*)"', source)
    if otlp_match is None:
        otlp_match = re.search(r"grafana_otlp_endpoint\s*:\s*str\s*=\s*'([^']*)'", source)

    assert otlp_match is not None, (
        "config.py declares grafana_otlp_endpoint without a default value. "
        "Change to: grafana_otlp_endpoint: str = '' "
        "See T-090."
    )


def test_config_grafana_otlp_token_has_default_empty_string() -> None:
    """
    config.py must declare grafana_otlp_token with a default of "".
    """
    source = read_backend_file("config.py")

    token_match = re.search(r'grafana_otlp_token\s*:\s*str\s*=\s*"([^"]*)"', source)
    if token_match is None:
        token_match = re.search(r"grafana_otlp_token\s*:\s*str\s*=\s*'([^']*)'", source)

    assert token_match is not None, (
        "config.py declares grafana_otlp_token without a default value. "
        "Change to: grafana_otlp_token: str = '' "
        "See T-090."
    )


def test_all_three_observability_fields_have_string_defaults() -> None:
    """
    All three observability fields must declare a default value (str = "").
    Pydantic raises ValidationError at startup if required fields are absent —
    that crashes fresh deploys without Sentry/OTLP configured.
    This test inspects the source so module caching cannot produce a false positive.
    """
    source = read_backend_file("config.py")

    for field_name in ("sentry_dsn", "grafana_otlp_endpoint", "grafana_otlp_token"):
        # Pattern: field_name: str = "..." with no URL in the default
        has_default = bool(
            re.search(
                rf'{field_name}\s*:\s*str\s*=\s*["\']',
                source,
            )
        )
        assert has_default, (
            f"config.py declares {field_name} as a required str with no default. "
            f"Change to: {field_name}: str = '' "
            "See T-090."
        )


# ---------------------------------------------------------------------------
# T-094 [Security posture] — WorkspaceService._load() footgun must be removed
# ---------------------------------------------------------------------------


def test_workspace_service_does_not_define_load_method() -> None:
    """
    WorkspaceService._load() queries by workspace_id alone with no ownership check.
    It is a footgun: any future caller that reaches for _load() instead of get()
    silently bypasses the T-082 security fix. The method must not exist.
    """
    source = read_backend_file("services", "workspace_service.py")

    # _load must not be defined as a method
    has_load_def = bool(
        re.search(r"def _load\s*\(", source)
    )
    assert not has_load_def, (
        "workspace_service.py still defines _load(). "
        "Inline the query into create() and delete _load(). See T-094."
    )


def test_workspace_service_create_loads_workspace_inline() -> None:
    """
    create() must load and return the workspace after inserting it, without
    delegating to a helper that lacks user_id filtering.
    """
    source = read_backend_file("services", "workspace_service.py")

    create_start = source.find("async def create")
    assert create_start != -1, "workspace_service.py must define async def create"

    next_method = source.find("\n    async def ", create_start + 1)
    create_body = source[create_start:next_method] if next_method != -1 else source[create_start:]

    # create() must do a db.execute(select(...)) to load the created workspace
    assert "select(" in create_body or "scalar_one" in create_body, (
        "workspace_service.create() does not perform an inline SELECT to load the workspace. "
        "Replace _load() call with an inline query. See T-094."
    )

    # Must NOT delegate to _load
    assert "_load(" not in create_body, (
        "workspace_service.create() still calls self._load(). "
        "Inline the SELECT and delete _load(). See T-094."
    )


# ---------------------------------------------------------------------------
# T-095 [Performance] — Eliminate double RS256 decode per request
# ---------------------------------------------------------------------------


def test_rate_limit_middleware_stores_jwt_claims_in_request_state() -> None:
    """
    RateLimitMiddleware must store verified JWT claims in request.state.jwt_claims
    after decoding. This lets downstream middleware and dependencies reuse the
    already-verified claims instead of performing a second RS256 decode.
    """
    source = read_backend_file("middleware", "rate_limit.py")

    assert "jwt_claims" in source, (
        "rate_limit.py does not write to request.state.jwt_claims. "
        "After decoding the token, add: request.state.jwt_claims = claims. "
        "See T-095."
    )

    assert "request.state" in source, (
        "rate_limit.py does not access request.state. "
        "Store claims there for downstream reuse. See T-095."
    )


def test_get_current_user_reads_cached_claims_from_request_state() -> None:
    """
    get_current_user() must check request.state.jwt_claims before re-verifying
    the token. When the rate limiter has already decoded and stored claims,
    the dependency must reuse them without a second RS256 operation.
    """
    source = read_backend_file("middleware", "auth.py")

    assert "jwt_claims" in source, (
        "middleware/auth.py does not check request.state.jwt_claims. "
        "Add: cached_claims = getattr(request.state, 'jwt_claims', None) "
        "and skip token verification when cached_claims is not None. "
        "See T-095."
    )

    assert "request.state" in source, (
        "get_current_user() does not read from request.state. See T-095."
    )


def test_csrf_middleware_reads_cached_claims_from_request_state() -> None:
    """
    CsrfMiddleware._session_id_from_authorization() must check request.state.jwt_claims
    before decoding the token itself. Three middleware layers each decoding RS256 is
    excessive; the first decode should populate state for all subsequent layers.
    """
    source = read_backend_file("middleware", "csrf.py")

    assert "jwt_claims" in source, (
        "middleware/csrf.py does not check request.state.jwt_claims. "
        "In _session_id_from_authorization(), read getattr(request.state, 'jwt_claims', None) "
        "before decoding. See T-095."
    )


# ---------------------------------------------------------------------------
# T-096 [Test quality] — Remove fragile _where_criteria introspection from mock
# ---------------------------------------------------------------------------


def test_workspace_test_mock_does_not_use_where_criteria() -> None:
    """
    _FakeDB.execute() in test_workspace.py must not introspect statement._where_criteria.
    This couples tests to a SQLAlchemy private internal that can change without notice.
    Use explicit requesting_user_id parameter on _FakeDB instead.
    """
    test_source_path = BACKEND_ROOT / "tests" / "test_workspace.py"
    assert test_source_path.exists(), "backend/tests/test_workspace.py must exist"

    source = test_source_path.read_text(encoding="utf-8")

    assert "_where_criteria" not in source, (
        "test_workspace.py still uses statement._where_criteria in _FakeDB.execute(). "
        "Replace with: _FakeDB(workspace=ws, requesting_user_id=uid) and compare "
        "workspace.user_id == self._requesting_user_id in execute(). See T-096."
    )


def test_workspace_test_fake_db_accepts_requesting_user_id_param() -> None:
    """
    _FakeDB must accept a requesting_user_id parameter so tests can express
    ownership expectations explicitly rather than relying on ORM statement parsing.
    """
    test_source_path = BACKEND_ROOT / "tests" / "test_workspace.py"
    source = test_source_path.read_text(encoding="utf-8")

    assert "requesting_user_id" in source, (
        "test_workspace.py _FakeDB does not have a requesting_user_id parameter. "
        "Add: def __init__(self, workspace=None, requesting_user_id=None). "
        "See T-096."
    )


def test_workspace_test_ownership_tests_pass_requesting_user_id() -> None:
    """
    Tests that verify ownership rejection must pass requesting_user_id to _FakeDB
    so the filtering is visible in test code (not hidden in ORM internals).
    """
    test_source_path = BACKEND_ROOT / "tests" / "test_workspace.py"
    source = test_source_path.read_text(encoding="utf-8")

    # Count how many times requesting_user_id is passed (should appear in several tests)
    occurrences = source.count("requesting_user_id=")
    assert occurrences >= 3, (
        f"requesting_user_id= appears only {occurrences} time(s) in test_workspace.py. "
        "Ownership-check tests (wrong-owner 404s and correct-owner success) should each "
        "pass requesting_user_id explicitly. See T-096."
    )
