"""
Harness contracts for Phase 5 code-review mitigation tasks T-067 through T-085.

Every test is RED before its corresponding task is implemented and GREEN after.
Do not edit this file unless the spec, plan, or review finding has changed.

Finding references map to docs/CODE_REVIEW.md:
  C1  → T-067   C2  → T-068   C3  → T-069   C4  → T-070
  C5  → T-071   C6  → T-072   C7  → T-073   C8  → T-074
  C9  → T-075   I1  → T-076   I2  → T-077   I3  → T-078
  I4  → T-079   I5  → T-080   I8  → T-081   I9  → T-082
  I10 → T-083   I11 → T-084   I14 → T-085
"""
from __future__ import annotations

import inspect
import re
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from conftest import import_backend, read_backend_file


REPO_ROOT = Path(__file__).resolve().parents[3]
BACKEND_ROOT = REPO_ROOT / "backend"
FRONTEND_SRC = REPO_ROOT / "frontend" / "src"


# ---------------------------------------------------------------------------
# T-067 [C1] — Credit service must not use FOR UPDATE on aggregate queries
# ---------------------------------------------------------------------------


def test_credit_deduct_does_not_combine_sum_with_for_update() -> None:
    """
    SELECT SUM(...).with_for_update() is invalid PostgreSQL and raises at runtime.
    The deduct() method must obtain the row lock via a pattern that PostgreSQL accepts.
    Acceptable patterns: SELECT rows FOR UPDATE then sum in Python, or a subquery approach.
    """
    source = read_backend_file("services", "credit_service.py")

    # Find the deduct method body
    deduct_start = source.find("async def deduct")
    assert deduct_start != -1, "credit_service.py must define async def deduct"

    # Find the next method to bound the deduct body
    next_method = source.find("\n    async def ", deduct_start + 1)
    deduct_body = source[deduct_start:next_method] if next_method != -1 else source[deduct_start:]

    # The invalid pattern: func.sum(...).with_for_update() or sum + with_for_update on same statement
    # We flag the combination of func.sum AND with_for_update in a single select() call
    has_sum = "func.sum" in deduct_body or "func.coalesce" in deduct_body
    has_for_update = "with_for_update" in deduct_body

    if has_sum and has_for_update:
        # Check if they appear on consecutive lines (same statement) — that's the bug
        lines = deduct_body.splitlines()
        sum_lines = {i for i, l in enumerate(lines) if "func.sum" in l or "func.coalesce" in l}
        lock_lines = {i for i, l in enumerate(lines) if "with_for_update" in l}
        # If any sum line and lock line are within 4 lines of each other, it's the bad pattern
        for sl in sum_lines:
            for ll in lock_lines:
                assert abs(sl - ll) > 4, (
                    "credit_service.deduct() uses SELECT SUM(...).with_for_update() — "
                    "this is invalid PostgreSQL syntax. Use row-level locking without aggregates. "
                    "See docs/CODE_REVIEW.md [C1] and T-067."
                )


@pytest.mark.asyncio
async def test_credit_deduct_is_callable_and_returns_ledger_entry() -> None:
    """deduct() must still accept (db, user_id, amount, reason) and return a CreditLedger."""
    module = import_backend("services.credit_service")
    service = module.CreditService()
    assert callable(getattr(service, "deduct", None)), (
        "CreditService must still expose async def deduct(db, user_id, amount, reason)"
    )


# ---------------------------------------------------------------------------
# T-068 [C2] — OAuth state parameter must be generated and verified
# ---------------------------------------------------------------------------


def test_auth_service_get_google_auth_url_does_not_discard_state() -> None:
    """
    get_google_auth_url() must store the OAuth state in Redis so handle_callback()
    can verify it. Discarding _state is a CSRF vulnerability.
    """
    source = read_backend_file("services", "auth_service.py")
    get_url_start = source.find("def get_google_auth_url")
    assert get_url_start != -1

    url_body = source[get_url_start:get_url_start + 600]

    # The state must not be silently discarded via `_state`
    assert "_state" not in url_body, (
        "get_google_auth_url() discards the OAuth state parameter (_state). "
        "Store the state in Redis and verify it in handle_callback(). "
        "See docs/CODE_REVIEW.md [C2] and T-068."
    )


def test_auth_callback_router_accepts_state_query_param() -> None:
    """
    /auth/callback must accept a 'state' query parameter for OAuth CSRF validation.
    """
    source = read_backend_file("routers", "auth.py")
    callback_start = source.find("async def google_callback")
    assert callback_start != -1, "routers/auth.py must define google_callback"

    callback_body = source[callback_start:callback_start + 400]
    assert "state" in callback_body, (
        "google_callback must accept a 'state' query parameter to verify OAuth CSRF. "
        "See docs/CODE_REVIEW.md [C2] and T-068."
    )


# ---------------------------------------------------------------------------
# T-069 [C3] — JWT token must not be accepted as a query parameter
# ---------------------------------------------------------------------------


def test_get_current_user_does_not_accept_token_query_param() -> None:
    """
    get_current_user() must not accept ?token= as an auth mechanism.
    Tokens in URLs appear in access logs and browser history.
    """
    source = read_backend_file("middleware", "auth.py")

    # The specific pattern: Query(..., alias="token") as a fallback for Bearer
    assert 'alias="token"' not in source and "alias='token'" not in source, (
        "middleware/auth.py accepts JWT via ?token= query parameter. "
        "Remove token_param — the SSE client uses Authorization headers. "
        "See docs/CODE_REVIEW.md [C3] and T-069."
    )

    assert 'token_param' not in source, (
        "token_param must be removed from get_current_user(). "
        "See docs/CODE_REVIEW.md [C3] and T-069."
    )


# ---------------------------------------------------------------------------
# T-070 [C4] — Rollback API field name must match the backend schema
# ---------------------------------------------------------------------------


def test_frontend_rollback_sends_version_number_field() -> None:
    """
    api.ts rollbackStage() must send { version_number: N } not { version: N }.
    The backend RollbackRequest schema requires version_number.
    """
    api_path = FRONTEND_SRC / "services" / "api.ts"
    assert api_path.exists(), "frontend/src/services/api.ts must exist"

    source = api_path.read_text(encoding="utf-8")
    rollback_start = source.find("export async function rollbackStage")
    assert rollback_start != -1, "api.ts must export rollbackStage"

    rollback_body = source[rollback_start:rollback_start + 300]

    assert "version_number" in rollback_body, (
        "rollbackStage() sends { version } but backend expects { version_number }. "
        "Change to `{ version_number: version }`. "
        "See docs/CODE_REVIEW.md [C4] and T-070."
    )

    assert "{ version }" not in rollback_body and "{ version: version }" not in rollback_body, (
        "rollbackStage() still sends { version } (bare shorthand). "
        "Must send { version_number: version }. "
        "See docs/CODE_REVIEW.md [C4] and T-070."
    )


def test_backend_rollback_schema_requires_version_number() -> None:
    """RollbackRequest must have version_number field (ge=1)."""
    module = import_backend("schemas.stage")
    request_cls = getattr(module, "RollbackRequest", None)
    assert request_cls is not None, "schemas/stage.py must define RollbackRequest"

    fields = request_cls.model_fields
    assert "version_number" in fields, (
        "RollbackRequest must have a 'version_number' field matching the API contract"
    )


# ---------------------------------------------------------------------------
# T-071 [C5] — Migration must create indexes on FK and query-critical columns
# ---------------------------------------------------------------------------


def test_index_migration_file_exists() -> None:
    """A migration adding performance indexes must exist after 0001_initial_schema."""
    versions_dir = BACKEND_ROOT / "migrations" / "versions"
    assert versions_dir.exists(), "migrations/versions/ directory must exist"

    migration_files = sorted(versions_dir.glob("*.py"))
    assert len(migration_files) >= 2, (
        "At least two migration files required: initial schema + indexes migration. "
        "See docs/CODE_REVIEW.md [C5] and T-071."
    )


def test_index_migration_creates_credit_ledger_user_id_index() -> None:
    """The indexes migration must index credit_ledger.user_id for balance queries."""
    versions_dir = BACKEND_ROOT / "migrations" / "versions"
    index_migrations = [
        f for f in sorted(versions_dir.glob("*.py"))
        if f.name != "0001_initial_schema.py"
    ]
    assert index_migrations, "No index migration file found. See T-071."

    combined = "\n".join(f.read_text(encoding="utf-8") for f in index_migrations)
    assert "credit_ledger" in combined and ("user_id" in combined), (
        "Index migration must create an index on credit_ledger(user_id). "
        "Balance SUM queries will full-scan as the ledger grows. "
        "See docs/CODE_REVIEW.md [C5] and T-071."
    )


def test_index_migration_creates_stages_workspace_id_index() -> None:
    """The indexes migration must index stages.workspace_id."""
    versions_dir = BACKEND_ROOT / "migrations" / "versions"
    index_migrations = [
        f for f in sorted(versions_dir.glob("*.py"))
        if f.name != "0001_initial_schema.py"
    ]
    assert index_migrations, "No index migration found. See T-071."

    combined = "\n".join(f.read_text(encoding="utf-8") for f in index_migrations)
    assert "stages" in combined and "workspace_id" in combined, (
        "Index migration must create an index on stages(workspace_id). "
        "See docs/CODE_REVIEW.md [C5] and T-071."
    )


def test_index_migration_creates_stage_versions_stage_id_index() -> None:
    """The indexes migration must index stage_versions.stage_id."""
    versions_dir = BACKEND_ROOT / "migrations" / "versions"
    index_migrations = [
        f for f in sorted(versions_dir.glob("*.py"))
        if f.name != "0001_initial_schema.py"
    ]
    assert index_migrations, "No index migration found. See T-071."

    combined = "\n".join(f.read_text(encoding="utf-8") for f in index_migrations)
    assert "stage_versions" in combined and "stage_id" in combined, (
        "Index migration must create an index on stage_versions(stage_id). "
        "See docs/CODE_REVIEW.md [C5] and T-071."
    )


# ---------------------------------------------------------------------------
# T-072 [C6] — /metrics endpoint must be protected
# ---------------------------------------------------------------------------


def test_metrics_endpoint_source_has_auth_check() -> None:
    """
    /metrics must check for an auth token or IP restriction.
    Unauthenticated metrics leak infrastructure details useful for recon.
    """
    source = read_backend_file("services", "observability.py")
    metrics_start = source.find('"/metrics"')
    if metrics_start == -1:
        metrics_start = source.find("'/metrics'")
    assert metrics_start != -1, "observability.py must define the /metrics route"

    # Look within 30 lines of the /metrics route definition for an auth check
    metrics_area = source[max(0, metrics_start - 200):metrics_start + 600]
    has_auth = any(
        kw in metrics_area
        for kw in ("metrics_token", "METRICS_TOKEN", "Authorization", "token", "Depends(")
    )
    assert has_auth, (
        "/metrics endpoint has no authentication. "
        "Add a bearer token check (metrics_token config var) or an IP allowlist. "
        "See docs/CODE_REVIEW.md [C6] and T-072."
    )


# ---------------------------------------------------------------------------
# T-073 [C7] — AcceptDiffRequest and ContentEditRequest must have size limits
# ---------------------------------------------------------------------------


def test_accept_diff_request_has_max_length_on_proposed_content() -> None:
    """AcceptDiffRequest.proposed_content must have a max_length constraint."""
    module = import_backend("schemas.stage")
    cls = getattr(module, "AcceptDiffRequest", None)
    assert cls is not None, "schemas/stage.py must define AcceptDiffRequest"

    field_info = cls.model_fields.get("proposed_content")
    assert field_info is not None

    metadata = field_info.metadata if hasattr(field_info, "metadata") else []
    has_max = any(
        getattr(m, "max_length", None) is not None
        for m in metadata
    )
    assert has_max, (
        "AcceptDiffRequest.proposed_content has no max_length — allows unbounded POST body. "
        "Add Field(max_length=100_000). "
        "See docs/CODE_REVIEW.md [C7] and T-073."
    )


def test_content_edit_request_has_max_length_on_content() -> None:
    """ContentEditRequest.content must have a max_length constraint."""
    module = import_backend("schemas.stage")
    cls = getattr(module, "ContentEditRequest", None)
    assert cls is not None, "schemas/stage.py must define ContentEditRequest"

    field_info = cls.model_fields.get("content")
    assert field_info is not None

    metadata = field_info.metadata if hasattr(field_info, "metadata") else []
    has_max = any(
        getattr(m, "max_length", None) is not None
        for m in metadata
    )
    assert has_max, (
        "ContentEditRequest.content has no max_length — allows unbounded POST body. "
        "Add Field(max_length=100_000). "
        "See docs/CODE_REVIEW.md [C7] and T-073."
    )


def test_accept_diff_max_length_is_reasonable() -> None:
    """AcceptDiffRequest.proposed_content max_length must be between 1_000 and 500_000."""
    module = import_backend("schemas.stage")
    cls = module.AcceptDiffRequest
    field_info = cls.model_fields.get("proposed_content")
    metadata = field_info.metadata if hasattr(field_info, "metadata") else []
    max_len = next(
        (getattr(m, "max_length") for m in metadata if getattr(m, "max_length", None)),
        None,
    )
    assert max_len is not None
    assert 1_000 <= max_len <= 500_000, (
        f"proposed_content max_length={max_len} is outside the expected 1k–500k range"
    )


# ---------------------------------------------------------------------------
# T-074 [C8] — SSE stream must catch SecurityError and ProviderError
# ---------------------------------------------------------------------------


def test_generate_stage_stream_catches_security_error() -> None:
    """
    The generate_stage SSE generator must catch SecurityError and emit an error event.
    Currently, SecurityError propagates silently, leaving the client stream hanging.
    """
    source = read_backend_file("routers", "stage.py")

    # Find generate endpoint (may be a helper or inline)
    assert "SecurityError" in source, (
        "routers/stage.py does not reference SecurityError in the stream path. "
        "generate_stage must catch SecurityError and yield an error SSE event. "
        "See docs/CODE_REVIEW.md [C8] and T-074."
    )

    # The SecurityError catch must be inside a generator or stream context
    # Check that it's not only in the import — it must appear in a try/except
    security_catches = [
        line.strip() for line in source.splitlines()
        if "SecurityError" in line and ("except" in line or "catch" in line.lower())
    ]
    assert security_catches, (
        "SecurityError is imported but never caught in the stream generator. "
        "Add `except SecurityError` inside the _stream() generator. "
        "See docs/CODE_REVIEW.md [C8] and T-074."
    )


def test_regenerate_stage_stream_also_catches_security_error() -> None:
    """
    regenerate_stage must have the same SecurityError catch as generate_stage.
    Both endpoints share the same vulnerability.
    """
    source = read_backend_file("routers", "stage.py")

    # If a shared helper exists, both endpoints delegate to it — that's acceptable
    has_shared_helper = "_build_generation_stream" in source or "_stream_helper" in source or "_generation_stream" in source
    has_duplicate_catch = source.count("except SecurityError") >= 2

    assert has_shared_helper or has_duplicate_catch, (
        "regenerate_stage does not catch SecurityError. "
        "Either extract a shared stream helper (T-085) or add the catch to both endpoints. "
        "See docs/CODE_REVIEW.md [C8] and T-074."
    )


# ---------------------------------------------------------------------------
# T-075 [C9] — Rate limiter must not use unverified JWT claims for user identity
# ---------------------------------------------------------------------------


def test_rate_limit_middleware_does_not_use_get_unverified_claims_for_user_id() -> None:
    """
    Extracting user_id from unverified JWT claims lets attackers spoof any user's
    rate limit bucket. The middleware must verify the token before trusting the sub.
    """
    source = read_backend_file("middleware", "rate_limit.py")

    # The dangerous pattern: get_unverified_claims + sub extraction
    has_unverified = "get_unverified_claims" in source
    has_sub = ".get(\"sub\")" in source or ".get('sub')" in source

    if has_unverified and has_sub:
        # Check if there's also a verify step nearby
        unverified_idx = source.find("get_unverified_claims")
        area = source[max(0, unverified_idx - 100):unverified_idx + 300]
        has_verify = "verify_access_token" in area or "decode(" in area
        assert has_verify, (
            "rate_limit.py uses get_unverified_claims() to extract user_id for rate limiting. "
            "An attacker can forge any user_id without a valid signature. "
            "Verify the token before using the sub claim. "
            "See docs/CODE_REVIEW.md [C9] and T-075."
        )


def test_csrf_middleware_does_not_use_get_unverified_claims_for_session_id() -> None:
    """
    Same issue in csrf.py — the session_id used to verify the CSRF token must
    come from a signature-verified JWT, not get_unverified_claims().
    """
    source = read_backend_file("middleware", "csrf.py")

    has_unverified = "get_unverified_claims" in source
    if has_unverified:
        unverified_idx = source.find("get_unverified_claims")
        area = source[max(0, unverified_idx - 100):unverified_idx + 300]
        has_verify = "verify_access_token" in area or "decode(" in area
        assert has_verify, (
            "csrf.py uses get_unverified_claims() to extract the session_id for CSRF verification. "
            "Replace with signature-verified claims. "
            "See docs/CODE_REVIEW.md [C9] and T-075."
        )


# ---------------------------------------------------------------------------
# T-076 [I1] — LLM adapters must be cached, not re-instantiated per generation
# ---------------------------------------------------------------------------


def test_llm_gateway_caches_adapter_instances() -> None:
    """
    get_llm() must return a cached adapter rather than constructing a new one
    on every call. New HTTP clients per generation exhaust file descriptors.
    """
    source = read_backend_file("services", "llm", "gateway.py")

    has_cache = (
        "_INSTANCES" in source
        or "_CACHE" in source
        or "_adapters" in source
        or "lru_cache" in source
        or "_instance" in source.lower()
    )
    assert has_cache, (
        "gateway.py has no adapter instance cache. "
        "get_llm() creates a new HTTP client on every call, exhausting file descriptors. "
        "Add a module-level _INSTANCES dict keyed by (provider, model). "
        "See docs/CODE_REVIEW.md [I1] and T-076."
    )


# ---------------------------------------------------------------------------
# T-077 [I2] — DB engine must configure production-grade connection pool
# ---------------------------------------------------------------------------


def test_database_engine_configures_connection_pool() -> None:
    """
    create_async_engine must set pool_size, max_overflow, and pool_recycle.
    Default pool_size=5 exhausts under real concurrent load.
    """
    source = read_backend_file("database.py")

    has_pool_config = "pool_size" in source
    assert has_pool_config, (
        "database.py uses default SQLAlchemy connection pool settings. "
        "Add pool_size, max_overflow, pool_timeout, and pool_recycle. "
        "See docs/CODE_REVIEW.md [I2] and T-077."
    )

    assert "max_overflow" in source, (
        "database.py must set max_overflow to control burst connection headroom. "
        "See docs/CODE_REVIEW.md [I2] and T-077."
    )


# ---------------------------------------------------------------------------
# T-078 [I3] — WorkspaceCreate must validate model against provider allowlist
# ---------------------------------------------------------------------------


def test_workspace_create_strips_legacy_llm_selection_fields() -> None:
    """WorkspaceCreate must strip the retired per-workspace provider/model fields.

    History: T-078 originally required a field_validator rejecting unknown
    models against VALID_MODELS[provider]. Model selection has since moved
    off the workspace entirely — routing is tier-policy driven (issue #17 /
    #26, services/llm/tier_policy.py) — so the schema now *removes* the
    legacy fields before validation (``_strip_legacy_llm_selection``). The
    original invariant (a hallucinated model string can never persist or
    reach generation) is preserved by stripping rather than rejecting.
    """
    source = read_backend_file("schemas", "workspace.py")
    assert "_strip_legacy_llm_selection" in source, (
        "WorkspaceCreate must strip retired provider/model inputs before "
        "validation so old clients keep working without reintroducing "
        "per-workspace model selection."
    )


def test_workspace_create_ignores_client_supplied_model() -> None:
    """A client-supplied (possibly hallucinated) model must not survive validation."""
    module = import_backend("schemas.workspace")
    WorkspaceCreate = module.WorkspaceCreate

    workspace = WorkspaceCreate(
        name="Test",
        problem_statement="A" * 60,
        provider="anthropic",
        model="gpt-99-hallucinated",
    )
    dumped = workspace.model_dump()
    assert "provider" not in dumped and "model" not in dumped, (
        "WorkspaceCreate must drop legacy provider/model inputs — model "
        "routing is owned by the tier policy, and a hallucinated model "
        "string must never persist on a workspace. See issue #17/#26."
    )


# ---------------------------------------------------------------------------
# T-079 [I4] — apply_diff must use index positions, not str.find
# ---------------------------------------------------------------------------


def test_apply_diff_signature_accepts_start_end_integers() -> None:
    """
    apply_diff must accept (original, start, end, replacement) positional args
    rather than (original, selected_text, replacement).
    str.find returns the first occurrence; indices are unambiguous.
    """
    module = import_backend("services.pipeline.diff_engine")
    sig = inspect.signature(module.apply_diff)
    params = list(sig.parameters.keys())

    assert "start" in params or "selection_start" in params, (
        "apply_diff still takes selected_text and uses str.find(). "
        "Replace with (original, start, end, replacement) to use unambiguous indices. "
        "See docs/CODE_REVIEW.md [I4] and T-079."
    )


def test_apply_diff_does_not_use_str_find() -> None:
    """apply_diff must not use str.find() to locate the selection."""
    source = read_backend_file("services", "pipeline", "diff_engine.py")
    apply_start = source.find("def apply_diff")
    assert apply_start != -1

    next_def = source.find("\ndef ", apply_start + 1)
    apply_body = source[apply_start:next_def] if next_def != -1 else source[apply_start:]

    assert ".find(" not in apply_body, (
        "apply_diff() still uses str.find() which is ambiguous for repeated text. "
        "Use the start/end integer indices from the RefineRequest. "
        "See docs/CODE_REVIEW.md [I4] and T-079."
    )


def test_apply_diff_correctness_with_duplicate_text() -> None:
    """apply_diff must replace the correct occurrence when text is repeated."""
    module = import_backend("services.pipeline.diff_engine")
    original = "foo bar foo"
    # Replace the second "foo" (positions 8–11)
    result = module.apply_diff(original, 8, 11, "baz")
    assert result == "foo bar baz", (
        f"apply_diff replaced wrong occurrence: got {result!r}. "
        "Index-based replacement must be used. "
        "See docs/CODE_REVIEW.md [I4] and T-079."
    )


# ---------------------------------------------------------------------------
# T-080 [I5] — Background eval task must have an error callback
# ---------------------------------------------------------------------------


def test_stage_manager_eval_task_has_done_callback() -> None:
    """Background eval tasks must log their exceptions instead of dying silently.

    History: T-080 required every ``asyncio.create_task(run_eval_background(...))``
    call to attach its own ``add_done_callback``. Scalability audit F6 unified
    all detached-task spawning behind ``BoundedTaskRegistry``
    (services/pipeline/background_tasks.py): eval work is now spawned via
    ``_schedule_stage_eval`` → ``_BACKGROUND_EVAL_TASKS.spawn(...)``, and the
    registry attaches the error-logging done-callback centrally. The invariant
    is unchanged — no fire-and-forget eval task may swallow its exception.
    """
    source = read_backend_file("services", "pipeline", "stage_manager.py")

    assert "asyncio.create_task(run_eval_background" not in source, (
        "Eval tasks must not be spawned with a bare asyncio.create_task — "
        "route them through _BACKGROUND_EVAL_TASKS.spawn so the registry's "
        "error-logging done-callback and advisory semaphore apply. F6."
    )
    assert "_BACKGROUND_EVAL_TASKS = BoundedTaskRegistry(" in source, (
        "stage_manager.py must register eval work in a BoundedTaskRegistry. "
        "See T-080 (original invariant) and scalability audit F6."
    )
    assert 'error_event="eval_background_failed"' in source, (
        "The eval registry must carry an error_event so failed eval tasks are "
        "logged. See docs/CODE_REVIEW.md [I5] and T-080."
    )

    registry_source = read_backend_file("services", "pipeline", "background_tasks.py")
    assert "task.add_done_callback(self._on_done)" in registry_source, (
        "BoundedTaskRegistry.spawn must attach its done-callback to every task. "
        "T-080 / F6."
    )
    assert "task.exception()" in registry_source and "logger.error" in registry_source, (
        "BoundedTaskRegistry._on_done must surface task exceptions via "
        "logger.error — silent background failures are invisible in production. "
        "docs/CODE_REVIEW.md [I5], T-080."
    )


# ---------------------------------------------------------------------------
# T-081 [I8] — credit_service.refund must be idempotent (double-refund guard)
# ---------------------------------------------------------------------------


def test_credit_service_refund_is_idempotent_in_source() -> None:
    """
    credit_service.refund() must check for an existing refund entry before
    inserting a new one. Double calls must not double-credit the user.
    """
    source = read_backend_file("services", "credit_service.py")

    refund_start = source.find("async def refund")
    assert refund_start != -1

    next_method = source.find("\n    async def ", refund_start + 1)
    refund_body = source[refund_start:next_method] if next_method != -1 else source[refund_start:]

    has_idempotency = (
        "refund:" in refund_body or
        f"refund:" in refund_body or
        "already" in refund_body.lower() or
        "duplicate" in refund_body.lower() or
        "existing" in refund_body.lower()
    )
    assert has_idempotency, (
        "credit_service.refund() has no duplicate-refund guard. "
        "A double call with the same ledger_entry_id credits the user twice. "
        "Check for an existing CreditLedger entry with reason=f'refund:{ledger_entry_id}'. "
        "See docs/CODE_REVIEW.md [I8] and T-081."
    )


@pytest.mark.asyncio
async def test_credit_service_refund_guard_does_not_double_credit() -> None:
    """Calling refund() twice with the same ledger_entry_id must insert only one entry."""
    from uuid import uuid4

    module = import_backend("services.credit_service")
    service = module.CreditService()

    inserted: list = []
    original_entry_id = uuid4()
    original_entry = MagicMock()
    original_entry.id = original_entry_id
    original_entry.amount = -10
    original_entry.user_id = uuid4()
    original_entry.reason = "generate"

    class FakeResult:
        def __init__(self, val):
            self._val = val
        def scalar_one_or_none(self):
            return self._val

    class FakeDB:
        def __init__(self):
            self._inserted = []
            self._call = 0

        async def execute(self, stmt):
            self._call += 1
            if self._call == 1:
                return FakeResult(original_entry)  # first: find the original deduction
            return FakeResult(MagicMock(id=uuid4(), amount=10, reason=f"refund:{original_entry_id}"))  # second: existing refund found

        def add(self, obj):
            self._inserted.append(obj)

        async def flush(self):
            pass

    db = FakeDB()
    # First call exercises the happy path (finds the original deduction).
    await service.refund(db, original_entry_id)

    class IdempotentDB:
        def __init__(self):
            self._inserted = []
            self._call = 0

        async def execute(self, stmt):
            self._call += 1
            if self._call == 1:
                return FakeResult(original_entry)
            # Simulates finding existing refund on second call
            existing_refund = MagicMock()
            existing_refund.reason = f"refund:{original_entry_id}"
            return FakeResult(existing_refund)

        def add(self, obj):
            self._inserted.append(obj)

        async def flush(self):
            pass

    idem_db = IdempotentDB()
    await service.refund(idem_db, original_entry_id)
    assert len(idem_db._inserted) == 0, (
        "refund() inserted a second entry even though a refund already exists for this ledger_entry_id. "
        "See docs/CODE_REVIEW.md [I8] and T-081."
    )


# ---------------------------------------------------------------------------
# T-082 [I9] — WorkspaceService.get must filter by user_id in the DB query
# ---------------------------------------------------------------------------


def test_workspace_service_get_includes_user_id_in_db_query() -> None:
    """
    WorkspaceService.get() must include user_id in the SQL WHERE clause —
    not fetch the workspace then check ownership in Python (timing oracle).
    """
    source = read_backend_file("services", "workspace_service.py")

    get_start = source.find("async def get(")
    assert get_start != -1, "workspace_service.py must define async def get()"

    next_method = source.find("\n    async def ", get_start + 1)
    get_body = source[get_start:next_method] if next_method != -1 else source[get_start:]

    # The query must filter by user_id at the DB level
    db_filter_present = (
        "user_id" in get_body and
        ("where(" in get_body.lower() or ".where" in get_body)
    )
    assert db_filter_present, (
        "WorkspaceService.get() fetches workspace then checks user_id in Python. "
        "This creates a timing oracle for IDOR enumeration. "
        "Add Workspace.user_id == user_id to the SQLAlchemy WHERE clause. "
        "See docs/CODE_REVIEW.md [I9] and T-082."
    )

    # The Python-level ownership check should no longer be needed
    python_idor_check = (
        "workspace.user_id != user_id" in get_body or
        "workspace.user_id == user_id" in get_body
    )
    assert not python_idor_check, (
        "WorkspaceService.get() still has a Python-level user_id check after fetching. "
        "Move the filter to the DB query and remove the post-fetch check. "
        "See docs/CODE_REVIEW.md [I9] and T-082."
    )


# ---------------------------------------------------------------------------
# T-083 [I10] — Refine inputs must pass the injection gate before reaching the LLM
# ---------------------------------------------------------------------------


def test_refine_guards_selected_text_before_llm() -> None:
    """Both refine inputs (instruction AND selected_text) must be security-gated.

    History: T-083 required the refine *router* to bleach-sanitize
    selected_text. The stage-screens audit (F1) deliberately removed bleach
    from this path — it mangled code-bearing selections with zero security
    value, and StageManager must raw-match selected_text against the stored
    document anyway. The controls that replaced it live in
    StageManager.refine(): the scan_async prompt-injection gate over both
    fields, and keyed-nonce untrusted-content fences around selected_text in
    the prompt. This test pins those replacements so neither input can reach
    the LLM unguarded.
    """
    source = read_backend_file("services", "pipeline", "stage_manager.py")

    refine_start = source.find("    async def refine(")
    assert refine_start != -1, "stage_manager.py must define StageManager.refine"
    next_method = source.find("\n    async def ", refine_start + 1)
    refine_body = source[refine_start:next_method] if next_method != -1 else source[refine_start:]

    # Both user-controlled fields go through the prompt-injection scan.
    assert '("selected_text", request.selected_text)' in refine_body, (
        "StageManager.refine() must run selected_text through the scan_async "
        "injection gate alongside instruction. Audit F1 replaced router-side "
        "bleach with this gate. See docs/CODE_REVIEW.md [I10] and T-083."
    )
    assert "scan_async" in refine_body, (
        "StageManager.refine() must call the scan_async prompt-injection gate "
        "on refine inputs before building the LLM prompt. T-083 / audit F1."
    )
    # selected_text is fenced as untrusted content inside the prompt.
    assert re.search(
        r"wrap_untrusted_content\(\s*['\"]selected_text['\"],\s*request\.selected_text\s*\)",
        refine_body,
    ), (
        "StageManager.refine() must wrap selected_text in keyed-nonce "
        "untrusted-content fences before it reaches the prompt. T-083 / audit F1."
    )


# ---------------------------------------------------------------------------
# T-084 [I11] — Workspace.tsx async handlers must use useCallback
# ---------------------------------------------------------------------------


def test_workspace_tsx_uses_usecallback_for_async_handlers() -> None:
    """
    Workspace.tsx redefines ~9 async handlers on every render.
    During streaming (8k+ tokens) this causes thousands of unnecessary child re-renders.
    All stable handlers must be wrapped in useCallback.
    """
    workspace_path = FRONTEND_SRC / "pages" / "Workspace.tsx"
    assert workspace_path.exists(), "frontend/src/pages/Workspace.tsx must exist"

    source = workspace_path.read_text(encoding="utf-8")

    use_callback_count = source.count("useCallback(")
    assert use_callback_count >= 5, (
        f"Workspace.tsx has only {use_callback_count} useCallback() calls. "
        "All async event handlers (requestGeneration, runRefine, acceptDiff, handleFinalise, "
        "handleContentChange, etc.) must be wrapped in useCallback. "
        "See docs/CODE_REVIEW.md [I11] and T-084."
    )

    # Verify useCallback is imported
    assert "useCallback" in source, (
        "Workspace.tsx does not import useCallback from React. "
        "See docs/CODE_REVIEW.md [I11] and T-084."
    )


# ---------------------------------------------------------------------------
# T-085 [I14] — generate_stage and regenerate_stage must share a stream helper
# ---------------------------------------------------------------------------


def test_generate_and_regenerate_share_stream_helper() -> None:
    """
    generate_stage and regenerate_stage contain copy-pasted _stream() bodies.
    Extract to a shared helper so fixes (like T-074) apply to both automatically.
    """
    source = read_backend_file("routers", "stage.py")

    # Duplication is detected by checking whether both handlers define the same
    # inline error handling, below.
    generate_idx = source.find("async def generate_stage")
    regenerate_idx = source.find("async def regenerate_stage")

    if generate_idx != -1 and regenerate_idx != -1:
        generate_body = source[generate_idx:regenerate_idx]
        regenerate_end = source.find("\n@router.", regenerate_idx + 1)
        regenerate_body = source[regenerate_idx:regenerate_end] if regenerate_end != -1 else source[regenerate_idx:]

        # If both bodies contain the exact same structure, duplication is present
        generate_has_dep_err = "StageDependencyError" in generate_body
        regenerate_has_dep_err = "StageDependencyError" in regenerate_body

        assert not (generate_has_dep_err and regenerate_has_dep_err), (
            "generate_stage and regenerate_stage both define StageDependencyError handling inline. "
            "Extract the shared _stream() body to a helper function so both benefit from all fixes. "
            "See docs/CODE_REVIEW.md [I14] and T-085."
        )
