"""Tests for agent-ready issues + non-clobbering AGENTS.md (Phase 21 — T-277).

Two pure units:

  - ``task_parser`` enrichment: the agent-ready issue body has all five fixed
    sections (even for a minimal task, via fallbacks), a parseable YAML header
    carrying ``task_ref``/``stage``/``spec_anchors``/``test_path``, the agent
    labels, stable SECTION_CONTRACTS-derived spec anchors, and sanitised free
    text. The Phase-13 ``body_md`` is left untouched (backward compatible).
  - ``agents_md_builder``: writes only inside delimited managed markers,
    round-trips pre-existing user content byte-for-byte, is idempotent
    (deterministic output), and fails safe on a malformed marker pair.
"""

from __future__ import annotations

from services.integrations import agents_md_builder
from services.integrations.task_parser import (
    AGENT_LABELS,
    compute_task_ref,
    parse_tasks,
)
from services.pipeline import agent_manual_service, github_export_service

_RICH_TASK = """\
### T-001: Add the rate governor

**Description:** Build a per-installation token bucket so one tenant cannot
starve another.

**Acceptance Criteria:** The governor backs off on 403/429 and requeues.

**Files:** `services/integrations/github_governor.py`

**Harness refs:** `harness/tests/test_governor.py::test_backoff`
"""

_MINIMAL_TASK = "### T-007: Just a description\n\n**Description:** Do the thing.\n"


# ===========================================================================
# Agent-ready issue body
# ===========================================================================


def test_agent_body_has_all_five_fixed_sections() -> None:
    task = parse_tasks(_RICH_TASK)[0]
    body = task.agent_body_md
    for section in (
        "## Context",
        "## Acceptance criteria",
        "## Files",
        "## The test that must pass",
        "## Spec links",
    ):
        assert section in body, f"missing {section}"


def test_agent_body_minimal_task_still_renders_all_sections() -> None:
    # The realistic generated-task shape: only a Description. Fallbacks must keep
    # every section present and useful.
    task = parse_tasks(_MINIMAL_TASK)[0]
    body = task.agent_body_md
    for section in (
        "## Context",
        "## Acceptance criteria",
        "## Files",
        "## The test that must pass",
        "## Spec links",
    ):
        assert section in body
    # Context lifts the description; the others fall back to useful guidance.
    assert "Do the thing." in body


def test_agent_body_yaml_header_is_parseable_and_carries_keys() -> None:
    task = parse_tasks(_RICH_TASK)[0]
    body = task.agent_body_md
    assert body.startswith("---\n")
    header = body.split("---\n", 2)[1]
    assert f"task_ref: {compute_task_ref('Add the rate governor')}" in header
    assert "stage: tasks" in header
    assert "spec_anchors:" in header
    assert "test_path:" in header
    # The cited harness test is carried as the test_path.
    assert "harness/tests/test_governor.py::test_backoff" in header


def test_agent_labels_are_attached() -> None:
    task = parse_tasks(_RICH_TASK)[0]
    assert task.labels == AGENT_LABELS
    assert task.labels == ("specforge", "stage:tasks", "ready-for-agent")


def test_spec_anchors_are_stable_and_section_contract_derived() -> None:
    # A task that mentions a canonical spec heading gets a stable slugged anchor.
    task = parse_tasks(
        "### T-001: Tighten the Threat Model\n\n**Description:** Update STRIDE.\n"
    )[0]
    header = task.agent_body_md.split("---\n", 2)[1]
    assert "PLAN.md#threat-model" in header


def test_spec_anchors_fall_back_to_doc_roots() -> None:
    task = parse_tasks("### T-001: Unmappable\n\n**Description:** xyzzy.\n")[0]
    header = task.agent_body_md.split("---\n", 2)[1]
    assert "SPEC.md" in header and "PLAN.md" in header


def test_agent_body_sanitises_untrusted_html() -> None:
    task = parse_tasks(
        "### T-001: Evil\n\n**Description:** Hi <script>alert(1)</script> there.\n"
    )[0]
    # The script block is removed entirely (tag + content); surrounding prose stays.
    assert "<script>" not in task.agent_body_md
    assert "alert(1)" not in task.agent_body_md
    assert "there." in task.agent_body_md


def test_phase13_body_md_is_unchanged() -> None:
    # Backward compatibility: the legacy body shape must be intact.
    task = parse_tasks(_RICH_TASK)[0]
    assert task.body_md.startswith("## Add the rate governor")
    assert "*Generated by [SpecForge](https://specforge.ai)*" in task.body_md


def test_enrichment_is_deterministic() -> None:
    a = parse_tasks(_RICH_TASK)[0].agent_body_md
    b = parse_tasks(_RICH_TASK)[0].agent_body_md
    assert a == b


# ===========================================================================
# Non-clobbering AGENTS.md
# ===========================================================================


_STAGES = {
    "spec": "# Spec\n\nThe product builds widgets.",
    "plan": "# Plan\n\nFastAPI + React.",
    "harness": "# Harness\n\nRun pytest.",
    "tasks": "### T-001: First\n\nx\n\n### T-002: Second\n\ny\n",
}


def test_build_agents_md_fresh_file_wraps_in_markers() -> None:
    out = agents_md_builder.build_agents_md(_STAGES, existing=None)
    assert agents_md_builder.MANAGED_START in out
    assert agents_md_builder.MANAGED_END in out
    assert "# Agent context" in out
    # The task list is rendered.
    assert "T-001: First" in out and "T-002: Second" in out


def test_agents_md_never_clobbers_existing_content() -> None:
    """Named acceptance test: a file with user content around a managed block —
    regenerate; the user content must be intact and the block refreshed."""
    user_before = "# My hand-written AGENTS.md\n\nKeep this intro.\n\n"
    user_after = "\n\n## House rules\n\nNever force-push.\n"
    old_block = (
        f"{agents_md_builder.MANAGED_START}\n# Agent context\n"
        f"stale\n{agents_md_builder.MANAGED_END}"
    )
    existing = f"{user_before}{old_block}{user_after}"

    out = agents_md_builder.build_agents_md(_STAGES, existing=existing)

    # User content before AND after the markers is preserved verbatim.
    assert out.startswith(user_before)
    assert out.endswith(user_after)
    assert "Keep this intro." in out
    assert "Never force-push." in out
    # The managed block was refreshed (stale content gone, new content in).
    assert "stale" not in out
    assert "See `SPEC.md` for the project mission" in out
    # Exactly one managed block.
    assert out.count(agents_md_builder.MANAGED_START) == 1
    assert out.count(agents_md_builder.MANAGED_END) == 1


def test_agents_md_is_idempotent() -> None:
    first = agents_md_builder.build_agents_md(_STAGES, existing=None)
    second = agents_md_builder.build_agents_md(_STAGES, existing=first)
    assert first == second  # re-sync with unchanged stages = byte-identical


def test_agents_md_no_markers_appends_and_preserves() -> None:
    existing = "# User's own file\n\nImportant notes.\n"
    out = agents_md_builder.build_agents_md(_STAGES, existing=existing)
    assert out.startswith(existing)
    assert "Important notes." in out
    assert agents_md_builder.MANAGED_START in out


def test_agents_md_malformed_half_marker_fails_safe() -> None:
    # A start marker with no end marker must NOT eat the rest of the file — and
    # must STAY safe across a second sync (the orphan start now precedes the real
    # block, the case a find-first pairing would clobber).
    existing = (
        f"# Notes\n\n{agents_md_builder.MANAGED_START}\n"
        "half-open, no end marker\n\nmore user text\n"
    )
    first = agents_md_builder.build_agents_md(_STAGES, existing=existing)
    assert "more user text" in first  # preserved (append, not truncate)
    assert "# Agent context" in first

    # Re-sync: the orphan start must not be paired with the real block's end.
    second = agents_md_builder.build_agents_md(_STAGES, existing=first)
    assert "more user text" in second  # still preserved on the second pass
    assert "half-open, no end marker" in second
    assert second.count(agents_md_builder.MANAGED_END) == 1  # one real block


def test_agents_md_sanitises_stage_content() -> None:
    stages = dict(_STAGES, spec="# Spec\n\n<script>evil()</script>safe text")
    out = agents_md_builder.build_agents_md(stages, existing=None)
    assert "<script>" not in out


def test_github_instruction_merge_preserves_user_content() -> None:
    existing = "# Team rules\n\nNever force-push.\n"
    generated = agents_md_builder.build_agents_md(_STAGES)
    merged = github_export_service._merge_instruction_file(existing, generated)
    assert merged.startswith(existing)
    assert merged.count(agents_md_builder.MANAGED_START) == 1


def test_github_instruction_cleanup_removes_only_managed_content() -> None:
    existing = agents_md_builder.build_agents_md(
        _STAGES, existing="# Team rules\n\nKeep this.\n"
    )
    cleaned, changed = github_export_service._remove_managed_instructions(existing)
    assert changed is True
    assert cleaned.startswith("# Team rules\n\nKeep this.\n")


def test_both_target_resolves_in_stable_filename_order() -> None:
    assert agent_manual_service.effective_targets("both") == (
        "codex",
        "claude_code",
    )
