"""Unit tests for task_parser (T-151).

The parser is pure — no fixtures, no DB, no I/O. Tests use inline string
content to verify every behaviour required by the acceptance criteria.
"""

from __future__ import annotations

from services.integrations.task_parser import ParsedTask, parse_tasks


def test_empty_string_returns_empty_list() -> None:
    assert parse_tasks("") == []


def test_content_with_no_task_headings_returns_empty_list() -> None:
    assert parse_tasks("## Some other markdown\n\nNot a task at all.") == []


def test_two_tasks_returns_two_parsed_tasks_in_document_order() -> None:
    content = "### T-001: Foo\n\nBody text\n\n### T-002: Bar\n\nOther body"
    result = parse_tasks(content)
    assert len(result) == 2
    assert [t.ref for t in result] == ["T-001", "T-002"]
    assert result[0].title == "Foo"
    assert result[1].title == "Bar"


def test_first_task_body_does_not_include_second_task() -> None:
    content = "### T-001: Foo\n\nBody one\n\n### T-002: Bar\n\nBody two"
    result = parse_tasks(content)
    assert "T-002" not in result[0].body_md
    assert "Bar" not in result[0].body_md
    assert "Body two" not in result[0].body_md


def test_body_md_contains_title_heading_and_raw_body() -> None:
    content = "### T-042: My Title\n\n**Description:** Hello world.\n\n- step 1\n"
    result = parse_tasks(content)
    assert len(result) == 1
    task = result[0]
    assert task.body_md.startswith("## My Title")
    assert "**Description:** Hello world." in task.body_md
    assert "- step 1" in task.body_md
    assert "*Generated by [Thought2Build](https://thought2build.com)*" in task.body_md


def test_task_with_no_body_below_heading_returns_minimal_body() -> None:
    content = "### T-001: Bare Task\n"
    result = parse_tasks(content)
    assert len(result) == 1
    task = result[0]
    assert task.ref == "T-001"
    assert task.title == "Bare Task"
    assert task.body_md.startswith("## Bare Task")
    # Even with no raw body, the footer must still be present.
    assert "*Generated by [Thought2Build](https://thought2build.com)*" in task.body_md


def test_task_title_with_special_characters_is_preserved_verbatim() -> None:
    content = (
        '### T-007: Quotes "and" colons: are kept (verbatim) — em-dash too!\n\nbody'
    )
    result = parse_tasks(content)
    assert result[0].title == 'Quotes "and" colons: are kept (verbatim) — em-dash too!'


def test_inner_heading_levels_are_preserved_in_body() -> None:
    content = (
        "### T-100: Outer\n\n"
        "## A wider heading should stay inside the body\n\n"
        "#### A deeper heading too\n\n"
        "### T-101: Sibling\n\n"
        "second body"
    )
    result = parse_tasks(content)
    assert len(result) == 2
    # ## and #### headings are preserved inside the first task's body.
    assert "## A wider heading should stay inside the body" in result[0].body_md
    assert "#### A deeper heading too" in result[0].body_md
    # The sibling ### task heading IS a delimiter and should not appear.
    assert "T-101" not in result[0].body_md


def test_returned_task_is_immutable() -> None:
    task = parse_tasks("### T-001: x\n\nbody")[0]
    assert isinstance(task, ParsedTask)
    # frozen=True dataclass — assignment raises AttributeError.
    import pytest

    with pytest.raises(AttributeError):
        task.ref = "T-999"  # type: ignore[misc]


def test_task_ref_must_match_T_dash_digits_format() -> None:
    # T-NN heading (only two digits is still digits — accepted)
    content = "### T-12: Two digits\n\nbody"
    result = parse_tasks(content)
    assert result[0].ref == "T-12"

    # T-A123 is NOT a valid ref (non-digit) so the parser ignores it.
    content2 = "### T-A123: not a real task ref\n\nbody"
    assert parse_tasks(content2) == []


def test_pure_function_is_idempotent() -> None:
    content = "### T-001: Foo\n\nbody"
    first = parse_tasks(content)
    second = parse_tasks(content)
    assert first == second
