import { useEffect } from "react"
import { Link } from "react-router-dom"
import { BrandLockup } from "../components/shared/BrandLogo"
import { MarkdownRenderer } from "../components/workspace/MarkdownRenderer"
import {
  LEGAL_CONTACT_EMAIL,
  LEGAL_ENTITY_DESCRIPTION,
  LEGAL_JURISDICTION,
  LEGAL_LAST_UPDATED,
} from "./legalConstants"

// Privacy Policy. Registered OUTSIDE the auth guard (must be readable
// without signing in) and must not import any authenticated client-side
// store — same constraint as LegalRetention.tsx and PublicWorkspaceView.
//
// Cookie disclosure lives in this page rather than a separate Cookie Policy:
// the backend sets exactly one cookie (refresh_token, strictly necessary —
// see backend/routers/auth.py), so a dedicated page would be unjustified.
//
// Every factual claim below is grounded in the app's actual behavior as of
// the date in legalConstants.ts. The India-specific legal framing (DPDPA) and
// the GDPR/CCPA section are informed by common practice, not
// jurisdiction-specific legal review — get real counsel review before real
// users sign up, and fill in the placeholders in legalConstants.ts first.

const PRIVACY_MARKDOWN = `
**Last updated: ${LEGAL_LAST_UPDATED}**

This Privacy Policy explains what personal data SpecForge collects, how it's
used, and who it's shared with. ${LEGAL_ENTITY_DESCRIPTION}

## 1. What We Collect

- **Account data** — email, Google account ID, name, and avatar image, from
  Google Sign-In (\`openid email profile\` scopes).
- **Content data** — your problem statement, clarification answers, and every
  generated spec/plan/harness/tasks artifact and version, entered or
  generated by you in a workspace.
- **Billing data** — your email address only, sent to our payment processor
  for checkout.
- **Integration data** — an encrypted GitHub access token or App installation
  record, only if you connect GitHub.

We do **not** store your IP address in our database. Your IP is processed
transiently (never persisted) for rate limiting, and may appear in short-lived
error-monitoring diagnostics if that's enabled (see **Who We Share It With**
below). We do not store payment card details — checkout is hosted entirely by
our payment processor.

## 2. How We Use It

To operate the four-stage generation pipeline you request, process credit
purchases, sync content to GitHub if you've connected it, keep the Service
reliable and secure, and respond when you contact us.

## 3. Legal Basis for Processing

${LEGAL_ENTITY_DESCRIPTION} As an India-based operator, our primary
obligations are under the **Digital Personal Data Protection Act, 2023
(DPDPA)** and the Information Technology (SPDI) Rules, 2011. We process your
data (as a **Data Principal** under the DPDPA) on the basis of your
**consent**, given when you sign in and use the Service, and you may withdraw
that consent at any time by ceasing use of the Service and requesting account
deletion (see **Your Rights** below). If you have a grievance about how we've
handled your personal data, contact us at ${LEGAL_CONTACT_EMAIL} — this is
our grievance-redressal channel.

If you're located in the European Economic Area, UK, or California, we also
recognize the rights described in the GDPR and CCPA respectively — in
practice, the rights in **Your Rights** below cover both frameworks; contact
us if you want to invoke a specific one by name.

## 4. Who We Share It With

We do not sell your data. We share it only as needed to run the Service:

- **Anthropic, OpenAI, Google (Gemini)** — always, one of the three per your
  workspace's provider choice — receive your idea, clarification answers, and
  prior stage content, as prompt context, to generate the artifact you
  request.
- **Lemon Squeezy or Razorpay** — depending on your region and how payments
  are currently configured — receives your email address only, no card data,
  for checkout. Lemon Squeezy is the Merchant of Record for its transactions;
  Razorpay is **not** (see our Terms of Service).
- **GitHub** — only if you connect it — receives the content you choose to
  export: spec/plan/harness/tasks files, issues, and pull requests, to your
  own repository.
- **Brave Search** — only if you enable it per workspace (off by default) —
  receives a query derived from your idea, to ground generation in current
  information.
- **Sentry** — only if we've enabled error monitoring — receives error
  diagnostics with secrets automatically stripped; may include your IP
  address and browser user-agent.
- **Langfuse** — only if we've enabled LLM observability — receives prompt
  and completion content (including your idea and generated artifacts), with
  secrets stripped.
- **Hosting/infrastructure provider** — to be finalised before any production
  launch — will receive whatever is needed to host and operate the Service
  (server logs, request metadata).

## 5. Public Sharing

If you enable public sharing on a workspace or a Storyboard, its content
becomes viewable by **anyone with the share link**, without needing to sign
in. This is off by default, entirely your choice, and you can disable it at
any time — disabling it removes public access (allowing briefly for caching)
going forward.

## 6. Cookies

We use a single, strictly necessary cookie:

| Cookie | Purpose | Type | Lifetime |
|---|---|---|---|
| \`refresh_token\` | Keeps you signed in between visits | Strictly necessary (first-party) | 7 days |

This cookie is essential for authentication, is protected with
industry-standard security attributes, and cannot be used to track you
across other sites. We don't use advertising, analytics, or third-party
tracking cookies.

## 7. Data Retention

We keep your active work indefinitely and prune only redundant history and
internal telemetry on a schedule. Deleting a workspace moves it to trash for a
window before permanent deletion, during which you can restore or export it.
See our full [Data Retention Policy](/legal/retention) for the exact windows,
which are versioned and may change over time.

## 8. Your Rights

You can, at any time:

- **Export** any workspace as a ZIP or PDF, or view/restore anything still in
  trash.
- **Request access, correction, or erasure** of your personal data, or object
  to a specific use of it, by contacting us at ${LEGAL_CONTACT_EMAIL}. Today
  this is a manual process we handle on request, not a self-service button —
  we'll confirm your identity and respond within a reasonable time.
- **Delete your account.** Contact us to request this; it may be delayed if
  you have unsettled billing debt on your account (see our Terms of Service).

## 9. Children's Privacy

SpecForge is not directed at, and is not intended for use by, anyone under
18. We do not knowingly collect data from anyone under 18.

## 10. International Data Transfers

Some of the third parties listed above (our LLM providers, payment
processors, and GitHub) process data outside ${LEGAL_JURISDICTION}. By using
the Service, you understand your data may be processed in other countries,
which may have different data protection laws than your own.

## 11. Security

We encrypt sensitive stored values (such as connected-integration tokens) at
rest, protect state-changing requests with CSRF tokens, and rate-limit
requests to reduce abuse. No system is perfectly secure, but we take
reasonable measures to protect your data.

## 12. Changes to This Policy

We may update this policy from time to time. We'll update the "Last updated"
date above when we do. Continued use of the Service after a change means you
accept the updated policy.

## 13. Contact

Questions about this policy, or a request to exercise your rights above?
Contact us at ${LEGAL_CONTACT_EMAIL}.
`.trim()

export default function LegalPrivacy() {
  useEffect(() => {
    document.title = "Privacy Policy — SpecForge"
    return () => {
      document.title = "SpecForge"
    }
  }, [])

  return (
    <div className="public-view-shell">
      <header className="public-view-cover">
        <BrandLockup variant="compact" className="public-view-brand" />
        <h1 className="public-view-title">Privacy Policy</h1>
      </header>

      <main className="public-view-content">
        <MarkdownRenderer content={PRIVACY_MARKDOWN} />
      </main>

      <footer className="public-view-footer">
        <p>
          <Link to="/legal/terms" className="public-view-footer-link">
            Terms of Service
          </Link>
          {" · "}
          <Link to="/legal/retention" className="public-view-footer-link">
            Data Retention Policy
          </Link>
          {" · "}
          <Link to="/" className="public-view-footer-link">
            ← Back to SpecForge
          </Link>
        </p>
      </footer>
    </div>
  )
}
