"""Thin async GitHub REST API wrapper with typed exceptions.

Scope discipline: this module has zero knowledge of business logic,
database, or SpecForge models. It receives a plaintext token and performs
only the operations the export service needs. All 401 responses raise
``GitHubTokenExpiredError`` before any other branch — the service layer
relies on this invariant to delete invalid tokens.

Supported operations: create_repo, get_file_sha, upsert_file,
create_issue, update_issue. No bidirectional sync: SpecForge never reads
issue state from GitHub.
"""

from __future__ import annotations

import base64
import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)

GITHUB_API_BASE = "https://api.github.com"
_DEFAULT_TIMEOUT_SECONDS = 30.0
_GITHUB_ACCEPT = "application/vnd.github+json"


# ---------------------------------------------------------------------------
# Typed exceptions
# ---------------------------------------------------------------------------


class GitHubNotConnectedError(Exception):
    """No GitHub integration exists for the current user."""


class GitHubRepoExistsError(Exception):
    """The requested repo name is already in use under the user's account."""


class GitHubTokenExpiredError(Exception):
    """GitHub returned 401 — the stored token is no longer valid.

    The service layer must delete the UserIntegration row when this is
    raised. SpecForge never retries with a known-invalid token.
    """


class GitHubRateLimitError(Exception):
    """GitHub returned 429 or a rate-limit primary/secondary signal."""


class GitHubAPIError(Exception):
    """Generic GitHub failure: non-2xx response not covered by the other types."""

    def __init__(self, status: int, message: str) -> None:
        super().__init__(f"GitHub API error {status}: {message}")
        self.status = status
        self.message = message


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------


class GitHubAPIClient:
    """Async wrapper around the GitHub REST API.

    The wrapper accepts a shared ``httpx.AsyncClient`` so callers can reuse
    a connection pool across multiple operations (the export service makes
    O(N) issue creates per push).
    """

    def __init__(self, token: str, client: httpx.AsyncClient) -> None:
        if not token:
            raise ValueError("GitHubAPIClient requires a non-empty token")
        self._token = token
        self._client = client

    # ----- repo -----

    async def create_repo(self, name: str, private: bool) -> dict[str, Any]:
        """POST /user/repos.

        Returns the full repo JSON on success.
        """
        body = {
            "name": name,
            "private": private,
            "auto_init": False,
            "description": "Generated by SpecForge",
        }
        response = await self._request("POST", "/user/repos", json=body)

        if response.status_code == 201:
            return response.json()

        if response.status_code == 422 and _is_already_exists(response):
            raise GitHubRepoExistsError(
                f"Repository {name!r} already exists in your GitHub account"
            )

        self._raise_for_status(response)
        # _raise_for_status always raises on non-2xx — this is unreachable.
        raise GitHubAPIError(response.status_code, response.text)

    # ----- contents (files) -----

    async def get_file_sha(self, repo: str, path: str) -> str | None:
        """GET /repos/{owner}/{repo}/contents/{path}.

        Returns the blob SHA if the file exists, or ``None`` on 404.
        """
        response = await self._request(
            "GET",
            f"/repos/{repo}/contents/{_quote_path(path)}",
        )
        if response.status_code == 404:
            return None
        if response.status_code == 200:
            body = response.json()
            sha = body.get("sha") if isinstance(body, dict) else None
            if isinstance(sha, str):
                return sha
            raise GitHubAPIError(
                response.status_code,
                f"contents response missing sha for {path}",
            )
        self._raise_for_status(response)
        return None  # unreachable

    async def upsert_file(
        self,
        repo: str,
        path: str,
        content: str,
        sha: str | None,
        commit_message: str,
    ) -> None:
        """PUT /repos/{owner}/{repo}/contents/{path}.

        When ``sha`` is provided this updates an existing file; otherwise
        it creates one. The content is base64-encoded.
        """
        encoded = base64.b64encode(content.encode("utf-8")).decode("ascii")
        body: dict[str, Any] = {
            "message": commit_message,
            "content": encoded,
        }
        if sha is not None:
            body["sha"] = sha

        response = await self._request(
            "PUT",
            f"/repos/{repo}/contents/{_quote_path(path)}",
            json=body,
        )
        if response.status_code in (200, 201):
            return

        self._raise_for_status(response)

    # ----- issues -----

    async def create_issue(self, repo: str, title: str, body: str) -> int:
        """POST /repos/{owner}/{repo}/issues. Returns the new issue number."""
        response = await self._request(
            "POST",
            f"/repos/{repo}/issues",
            json={"title": title, "body": body},
        )
        if response.status_code == 201:
            data = response.json()
            number = data.get("number") if isinstance(data, dict) else None
            if isinstance(number, int):
                return number
            raise GitHubAPIError(
                response.status_code,
                "issue creation succeeded but response missing 'number'",
            )

        self._raise_for_status(response)
        raise GitHubAPIError(response.status_code, response.text)  # unreachable

    async def update_issue(
        self,
        repo: str,
        number: int,
        title: str,
        body: str,
    ) -> None:
        """PATCH /repos/{owner}/{repo}/issues/{number}."""
        response = await self._request(
            "PATCH",
            f"/repos/{repo}/issues/{number}",
            json={"title": title, "body": body},
        )
        if response.status_code == 200:
            return
        self._raise_for_status(response)

    # ----- internals -----

    async def _request(
        self,
        method: str,
        path: str,
        *,
        json: dict[str, Any] | None = None,
    ) -> httpx.Response:
        url = f"{GITHUB_API_BASE}{path}"
        headers = {
            "Authorization": f"Bearer {self._token}",
            "Accept": _GITHUB_ACCEPT,
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "SpecForge/1.0",
        }
        try:
            response = await self._client.request(
                method,
                url,
                headers=headers,
                json=json,
            )
        except httpx.HTTPError as exc:
            raise GitHubAPIError(0, f"network error: {exc}") from exc

        # 401 is mapped here before anything else so callers cannot
        # accidentally treat it as a generic API error.
        if response.status_code == 401:
            raise GitHubTokenExpiredError(
                "GitHub returned 401; the stored token is no longer valid"
            )
        return response

    def _raise_for_status(self, response: httpx.Response) -> None:
        status = response.status_code
        if status < 400:
            return

        # 401 is already short-circuited in _request, but guard here too
        # for paranoia in case a subclass bypasses _request.
        if status == 401:
            raise GitHubTokenExpiredError(
                "GitHub returned 401; the stored token is no longer valid"
            )
        if status == 403 and _is_rate_limited(response):
            raise GitHubRateLimitError("GitHub API rate limit reached")
        if status == 429:
            raise GitHubRateLimitError("GitHub API rate limit reached")

        message = _short_error_message(response)
        raise GitHubAPIError(status, message)


def make_github_client(token: str, client: httpx.AsyncClient) -> GitHubAPIClient:
    """Factory function for dependency injection.

    Tests inject a custom ``httpx.AsyncClient`` (often with a ``MockTransport``)
    via this entry point so the production call sites can build clients
    against the real ``httpx.AsyncClient`` without modification.
    """
    return GitHubAPIClient(token=token, client=client)


# ---------------------------------------------------------------------------
# Module helpers
# ---------------------------------------------------------------------------


def _is_already_exists(response: httpx.Response) -> bool:
    """Return True if a 422 response indicates a name collision."""
    try:
        body = response.json()
    except ValueError:
        return False
    if not isinstance(body, dict):
        return False
    errors = body.get("errors") or []
    if isinstance(errors, list):
        for err in errors:
            if isinstance(err, dict):
                msg = (err.get("message") or "").lower()
                if "already exists" in msg or err.get("code") == "already_exists":
                    return True
    message = (body.get("message") or "").lower()
    return "already exists" in message or "name already exists" in message


def _is_rate_limited(response: httpx.Response) -> bool:
    """Distinguish a permission-denied 403 from a rate-limit 403."""
    remaining = response.headers.get("x-ratelimit-remaining")
    if remaining == "0":
        return True
    try:
        body = response.json()
    except ValueError:
        return False
    if not isinstance(body, dict):
        return False
    message = (body.get("message") or "").lower()
    return "rate limit" in message or "abuse" in message or "secondary rate" in message


def _short_error_message(response: httpx.Response) -> str:
    """Extract a concise error message from a GitHub response body."""
    try:
        body = response.json()
    except ValueError:
        return (response.text or "")[:200]
    if isinstance(body, dict):
        message = body.get("message")
        if isinstance(message, str):
            return message[:200]
    return (response.text or "")[:200]


def _quote_path(path: str) -> str:
    """GitHub Contents API accepts paths containing slashes verbatim.

    We strip any leading slash and forbid traversal segments — callers
    should pass repo-relative paths.
    """
    cleaned = path.lstrip("/")
    if ".." in cleaned.split("/"):
        raise ValueError(f"invalid path with traversal segment: {path!r}")
    return cleaned
