"""Pure deterministic parser that extracts T-NNN tasks from TASKS.md.

Zero I/O. Zero external dependencies. Zero hidden state. Takes a string,
returns a list. Fully testable with inline fixtures.

Output shape is the GitHub Issue body the export service hands to
``GitHubAPIClient.create_issue``. The body preserves the original task
subsections verbatim (Description, Steps, Acceptance Criteria, etc.)
followed by a footer crediting SpecForge.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

_TASK_HEADING = re.compile(r"^###\s+(T-\d+):\s+(.+?)\s*$", re.MULTILINE)
_FOOTER = "*Generated by [SpecForge](https://specforge.ai)*"


@dataclass(frozen=True)
class ParsedTask:
    """A single task extracted from TASKS.md.

    Attributes:
        ref: The task reference, e.g. ``"T-001"``.
        title: The heading text after the ref, e.g. ``"Set up project structure"``.
        body_md: The full GitHub Issue body — title heading + raw task body +
            SpecForge footer. Safe to pass directly to ``create_issue``.
    """

    ref: str
    title: str
    body_md: str


def parse_tasks(content: str) -> list[ParsedTask]:
    """Extract every ``### T-NNN: <title>`` task from TASKS.md content.

    Returns tasks in document order. Empty input or input with no T-NNN
    headings returns an empty list.

    The body for each task is everything between its heading and the next
    ``###`` heading (or end of document), stripped of leading and trailing
    whitespace. Headings of any other depth (``##``, ``####``, ``#####``)
    inside a task body are preserved verbatim — only sibling ``###``
    headings act as task delimiters.
    """
    if not content:
        return []

    matches = list(_TASK_HEADING.finditer(content))
    if not matches:
        return []

    tasks: list[ParsedTask] = []
    for index, match in enumerate(matches):
        ref = match.group(1)
        title = match.group(2).strip()

        body_start = match.end()
        body_end = (
            matches[index + 1].start() if index + 1 < len(matches) else len(content)
        )
        raw_body = content[body_start:body_end].strip()

        body_md = _format_issue_body(title=title, raw_body=raw_body)
        tasks.append(ParsedTask(ref=ref, title=title, body_md=body_md))

    return tasks


def _format_issue_body(*, title: str, raw_body: str) -> str:
    """Render a GitHub Issue body for the task.

    The format mirrors the source TASKS.md: ``## {title}`` heading, the
    raw subsections preserved verbatim, a horizontal rule, and a SpecForge
    footer. Two trailing newlines keep the footer separated when the
    issue is pasted into other markdown contexts.
    """
    sections: list[str] = [f"## {title}"]
    if raw_body:
        sections.append(raw_body)
    sections.append("---")
    sections.append(_FOOTER)
    return "\n\n".join(sections) + "\n"
