"""Reconcile tracked GitHub issues against the current Tasks specification."""

from __future__ import annotations

from typing import Any
from uuid import UUID

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from models.integration_push_task import IntegrationPushTask

logger = structlog.get_logger(__name__)

_OBSOLETE_TASK_NOTE = (
    "This task was removed from the current Thought2Build Tasks specification and "
    "is no longer tracked by this workspace. Closing it — reopen it if the work "
    "is still needed outside the current spec.\n\n"
    "*Generated by [Thought2Build](https://thought2build.com)*"
)


async def retire_obsolete_task_issues(
    db: AsyncSession,
    client: Any,
    repo: str,
    push_id: UUID,
    current_refs: set[str],
) -> set[str]:
    """Close and retire tracked issues absent from the current Tasks version.

    The GitHub issue is preserved as reversible history, while its live mapping
    is removed so completion totals describe the current spec rather than all
    tasks ever exported. GitHub state makes retries idempotent: an issue already
    closed (including one closed by an earlier partial attempt) is not commented
    or closed again. A missing issue is safe to retire locally; non-404 API
    failures are raised by ``get_issue_state`` and keep the mapping intact.
    """
    rows = list(
        (
            await db.execute(
                select(IntegrationPushTask).where(
                    IntegrationPushTask.push_id == push_id
                )
            )
        ).scalars()
    )
    retired: set[str] = set()
    for row in rows:
        if row.task_ref in current_refs:
            continue
        state = await client.get_issue_state(repo, row.external_issue_number)
        if state != "closed" and state is not None:
            await client.add_issue_comment(
                repo, row.external_issue_number, _OBSOLETE_TASK_NOTE
            )
            await client.close_issue(repo, row.external_issue_number)
        await db.delete(row)
        retired.add(row.task_ref)
        logger.info(
            "github.export.task_retired",
            push_id=str(push_id),
            task_ref=row.task_ref,
            issue_number=row.external_issue_number,
            github_state=state or "missing",
        )
    if retired:
        await db.commit()
    return retired
