"""Pure deterministic parser that extracts T-NNN tasks from TASKS.md.

Zero I/O. Zero external dependencies. Zero hidden state. Takes a string,
returns a list. Fully testable with inline fixtures.

Output shape is the GitHub Issue body the export service hands to
``GitHubAPIClient.create_issue``. The body preserves the original task
subsections verbatim (Description, Steps, Acceptance Criteria, etc.)
followed by a footer crediting SpecForge.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass

_TASK_HEADING = re.compile(r"^###\s+(T-\d+):\s+(.+?)\s*$", re.MULTILINE)
_FOOTER = "*Generated by [SpecForge](https://specforge.ai)*"

# Collapse all interior whitespace runs so trivial reflowing of a title does not
# change its identity.
_WHITESPACE = re.compile(r"\s+")


def compute_task_ref(title: str, *, stage: str = "tasks") -> str:
    """Return the stable, content-derived matching key for a task (spec §10,
    Assumption 23).

    This is the single dedup/identity key for an :class:`IntegrationPushTask`.
    It is **content-derived** — a short hash of the normalized task title scoped
    by ``stage`` — and deliberately does **not** depend on the human-readable
    ``T-NNN`` number. That is the load-bearing property: a refinement that
    renumbers ``T-001`` → ``T-002`` while keeping the same title yields the same
    ``task_ref``, so re-export/reconcile/increment sync update the *same* GitHub
    Issue instead of opening a duplicate. The ``T-NNN: {title}`` string remains
    the issue *title*; matching is always on this ref.

    Defined in Phase A so export (T-269), agent issues (T-277), and increments
    (T-279/T-280) all share one matching key rather than re-deriving it.

    Normalization (case- and whitespace-folded) keeps the key stable across
    cosmetic edits; the ``stage`` prefix prevents collisions between same-titled
    tasks that originate in different stages. The 48-bit hex prefix is amply
    collision-resistant across a single workspace's task set.
    """
    normalized = _WHITESPACE.sub(" ", title).strip().casefold()
    digest = hashlib.sha256(f"{stage}\x1f{normalized}".encode()).hexdigest()
    return f"task-{digest[:12]}"


@dataclass(frozen=True)
class ParsedTask:
    """A single task extracted from TASKS.md.

    Attributes:
        ref: The task reference, e.g. ``"T-001"``.
        title: The heading text after the ref, e.g. ``"Set up project structure"``.
        body_md: The full GitHub Issue body — title heading + raw task body +
            SpecForge footer. Safe to pass directly to ``create_issue``.
    """

    ref: str
    title: str
    body_md: str


def parse_tasks(content: str) -> list[ParsedTask]:
    """Extract every ``### T-NNN: <title>`` task from TASKS.md content.

    Returns tasks in document order. Empty input or input with no T-NNN
    headings returns an empty list.

    The body for each task is everything between its heading and the next
    ``###`` heading (or end of document), stripped of leading and trailing
    whitespace. Headings of any other depth (``##``, ``####``, ``#####``)
    inside a task body are preserved verbatim — only sibling ``###``
    headings act as task delimiters.
    """
    if not content:
        return []

    matches = list(_TASK_HEADING.finditer(content))
    if not matches:
        return []

    tasks: list[ParsedTask] = []
    for index, match in enumerate(matches):
        ref = match.group(1)
        title = match.group(2).strip()

        body_start = match.end()
        body_end = (
            matches[index + 1].start() if index + 1 < len(matches) else len(content)
        )
        raw_body = content[body_start:body_end].strip()

        body_md = _format_issue_body(title=title, raw_body=raw_body)
        tasks.append(ParsedTask(ref=ref, title=title, body_md=body_md))

    return tasks


def _format_issue_body(*, title: str, raw_body: str) -> str:
    """Render a GitHub Issue body for the task.

    The format mirrors the source TASKS.md: ``## {title}`` heading, the
    raw subsections preserved verbatim, a horizontal rule, and a SpecForge
    footer. Two trailing newlines keep the footer separated when the
    issue is pasted into other markdown contexts.
    """
    sections: list[str] = [f"## {title}"]
    if raw_body:
        sections.append(raw_body)
    sections.append("---")
    sections.append(_FOOTER)
    return "\n\n".join(sections) + "\n"
